/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Estructuras.Array;
import Estructuras.Cola;
import Estructuras.ListaArray;
import Estructuras.ListaDoble;
import Estructuras.ListaSimple;
import Estructuras.Pila;
import controlador.CtlEstructuras;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cancion;

/**
 *
 * @author Pepe
 */
public class pnlEstructuras extends javax.swing.JPanel {

    CtlEstructuras ctlEstructuras;
    ListaSimple listaSimple;
    ListaDoble listaDoble;
    Pila pila;
    Cola cola;
    ListaArray arrayList;
    Array array;

    public pnlEstructuras() {
        initComponents();
        ctlEstructuras = new CtlEstructuras();
        listaSimple = new ListaSimple();
        listaDoble = new ListaDoble();
        pila = new Pila();
        cola = new Cola();
        arrayList = new ListaArray();
        array = new Array();

        lblDuracion.setText("");
        lblId.setText("");
        lblLanzamiento.setText("");
        lblNombre.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbxRegistrar = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreBuscar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDuracionBuscar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtLanzamientoBuscar = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        lblLanzamiento = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblDuracion = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        txtNombreModificar = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtDuracionModificar = new javax.swing.JTextField();
        txtLanzamientoModificar = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbxEstructuras = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "ESTRUCTURAS DE DATOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "REGISTRAR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        jLabel1.setText("Cantidad de datos");

        cbxRegistrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleecione opcion", "10", "100", "1000", "10000", "100000", "500000", "1000000" }));

        btnRegistrar.setText("CARGAR DATOS");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbxRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "BUSCAR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        jLabel3.setText("Nombre");

        jLabel4.setText("Duracion");

        jLabel5.setText("Lanzamiento");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Resultado Busqueda"));

        lblLanzamiento.setText("jLabel10");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("LANZAMIENTO");

        lblDuracion.setText("jLabel11");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("DURACION");

        lblNombre.setText("jLabel13");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("NOMBRE");

        lblId.setText("jLabel12");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("ID");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(120, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLanzamiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDuracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(3, 3, 3)
                .addComponent(lblId)
                .addGap(8, 8, 8)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDuracion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLanzamiento)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnBuscar.setText("BUSCAR DATOS");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDuracionBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLanzamientoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDuracionBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtLanzamientoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(14, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "MODIFICAR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        jLabel16.setText("Nombre");

        jLabel17.setText("Duracion");

        jLabel18.setText("Lanzamiento");

        btnModificar.setText("MODIFICAR DATOS");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(32, 32, 32)
                        .addComponent(txtNombreModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel17)
                        .addGap(27, 27, 27)
                        .addComponent(txtDuracionModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLanzamientoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtNombreModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtDuracionModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtLanzamientoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "ELIMINAR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        btnEliminar.setText("ELIMINAR DATOS");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Estructura de datos");

        cbxEstructuras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Opcion", "Lista simple", "Lista doble", "Pila", "Cola", "ArrayList", "Array", "Hash", "Arbol", "Arbol AVL" }));

        jButton1.setText("NUEVA ESTRUCTURA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel2)
                        .addGap(55, 55, 55)
                        .addComponent(cbxEstructuras, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxEstructuras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel15.setText("DATOS DE CANCION");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel15)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                        .addGap(30, 30, 30))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        double inicioTiempo;
        double tiempoFin;
        double totalTime;
        if (cbxRegistrar.getSelectedIndex() != 0) {
            if (cbxEstructuras.getSelectedIndex() == 1) {
                try {
                    ctlEstructuras.llenarLista(Integer.parseInt(cbxRegistrar.getSelectedItem().toString()));
                    inicioTiempo = System.nanoTime();
                    listaSimple.insertarListaSimple(Integer.parseInt(cbxRegistrar.getSelectedItem().toString()));
                    tiempoFin = System.nanoTime();
                    totalTime = tiempoFin - inicioTiempo;
                    ctlEstructuras.ingresarTiempo("Insertar", "Lista simple", totalTime);
                    listarCancionesLitaSimple();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(pnlEstructuras.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(pnlEstructuras.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            if (cbxEstructuras.getSelectedIndex() == 2) {
                try {
                    ctlEstructuras.llenarLista(Integer.parseInt(cbxRegistrar.getSelectedItem().toString()));
                    inicioTiempo = System.nanoTime();
                    listaDoble.insertarListaDoble(Integer.parseInt(cbxRegistrar.getSelectedItem().toString()));
                    tiempoFin = System.nanoTime();
                    totalTime = tiempoFin - inicioTiempo;
                    ctlEstructuras.ingresarTiempo("Insertar", "Lista doble", totalTime);
                    listarCancionesListaDoble();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(pnlEstructuras.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(pnlEstructuras.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if (cbxEstructuras.getSelectedIndex() == 3) {
                try {
                    ctlEstructuras.llenarLista(Integer.parseInt(cbxRegistrar.getSelectedItem().toString()));
                    inicioTiempo = System.nanoTime();
                    pila.insertarPila(Integer.parseInt(cbxRegistrar.getSelectedItem().toString()));
                    tiempoFin = System.nanoTime();
                    totalTime = tiempoFin - inicioTiempo;
                    ctlEstructuras.ingresarTiempo("Insertar", "Pila", totalTime);
                    listarCancionesPila();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(pnlEstructuras.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(pnlEstructuras.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            if (cbxEstructuras.getSelectedIndex() == 4) {
                try {
                    ctlEstructuras.llenarLista(Integer.parseInt(cbxRegistrar.getSelectedItem().toString()));
                    inicioTiempo = System.nanoTime();
                    cola.insertarCola(Integer.parseInt(cbxRegistrar.getSelectedItem().toString()));
                    tiempoFin = System.nanoTime();
                    totalTime = tiempoFin - inicioTiempo;
                    ctlEstructuras.ingresarTiempo("Insertar", "Pila", totalTime);
                    listarCancionesCola();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(pnlEstructuras.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(pnlEstructuras.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if (cbxEstructuras.getSelectedIndex() == 5) {
                try {
                    ctlEstructuras.llenarLista(Integer.parseInt(cbxRegistrar.getSelectedItem().toString()));
                    inicioTiempo = System.nanoTime();
                    arrayList.insertarArrayList(Integer.parseInt(cbxRegistrar.getSelectedItem().toString()));
                    tiempoFin = System.nanoTime();
                    totalTime = tiempoFin - inicioTiempo;
                    ctlEstructuras.ingresarTiempo("Insertar", "ArrayList", totalTime);
                    listarCancionesArrayList();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(pnlEstructuras.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(pnlEstructuras.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if (cbxEstructuras.getSelectedIndex() == 6) {
                try {
                    ctlEstructuras.llenarLista(Integer.parseInt(cbxRegistrar.getSelectedItem().toString()));
                    inicioTiempo = System.nanoTime();
                    array.insertarArray(Integer.parseInt(cbxRegistrar.getSelectedItem().toString()));
                    tiempoFin = System.nanoTime();
                    totalTime = tiempoFin - inicioTiempo;
                    ctlEstructuras.ingresarTiempo("Insertar", "Array", totalTime);
                    listarCancionesArrayList();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(pnlEstructuras.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(pnlEstructuras.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Cancion cancion;
        double inicioTiempo;
        double tiempoFin;
        double totalTime;
        if (cbxEstructuras.getSelectedIndex() == 1) {
            inicioTiempo = System.nanoTime();
            cancion = listaSimple.buscarListaSimple(txtDuracionBuscar.getText(), txtNombreBuscar.getText(), txtLanzamientoBuscar.getText());
            tiempoFin = System.nanoTime();
            totalTime = tiempoFin - inicioTiempo;
            ctlEstructuras.ingresarTiempo("Buscar", "Lista simple", totalTime);
            if (cancion != null) {
                lblId.setText("" + cancion.getId());
                lblDuracion.setText(cancion.getDuracion() + "");
                lblLanzamiento.setText(cancion.getLanzamiento() + "");
                lblNombre.setText(cancion.getNombre());
            } else {
                JOptionPane.showMessageDialog(null, "No se encontro la Cancion");
            }
            txtDuracionBuscar.setText("");
            txtLanzamientoBuscar.setText("");
            txtNombreBuscar.setText("");
        }

        if (cbxEstructuras.getSelectedIndex() == 2) {
            inicioTiempo = System.nanoTime();
            cancion = listaDoble.buscarListaDoble(txtDuracionBuscar.getText(), txtNombreBuscar.getText(), txtLanzamientoBuscar.getText());
            tiempoFin = System.nanoTime();
            totalTime = tiempoFin - inicioTiempo;
            ctlEstructuras.ingresarTiempo("Buscar", "Lista doble", totalTime);
            if (cancion != null) {
                lblId.setText("" + cancion.getId());
                lblDuracion.setText(cancion.getDuracion() + "");
                lblLanzamiento.setText(cancion.getLanzamiento() + "");
                lblNombre.setText(cancion.getNombre());
            } else {
                JOptionPane.showMessageDialog(null, "No se encontro la Cancion");
            }
            txtDuracionBuscar.setText("");
            txtLanzamientoBuscar.setText("");
            txtNombreBuscar.setText("");
        }

        if (cbxEstructuras.getSelectedIndex() == 3) {
            inicioTiempo = System.nanoTime();
            cancion = pila.buscarPila(txtDuracionBuscar.getText(), txtNombreBuscar.getText(), txtLanzamientoBuscar.getText());
            tiempoFin = System.nanoTime();
            totalTime = tiempoFin - inicioTiempo;
            ctlEstructuras.ingresarTiempo("Buscar", "Pila", totalTime);
            if (cancion != null) {
                lblId.setText("" + cancion.getId());
                lblDuracion.setText(cancion.getDuracion() + "");
                lblLanzamiento.setText(cancion.getLanzamiento() + "");
                lblNombre.setText(cancion.getNombre());
            } else {
                JOptionPane.showMessageDialog(null, "No se encontro la Cancion");
            }
            txtDuracionBuscar.setText("");
            txtLanzamientoBuscar.setText("");
            txtNombreBuscar.setText("");
        }
        if (cbxEstructuras.getSelectedIndex() == 4) {
            inicioTiempo = System.nanoTime();
            cancion = cola.buscarCola(txtDuracionBuscar.getText(), txtNombreBuscar.getText(), txtLanzamientoBuscar.getText());
            tiempoFin = System.nanoTime();
            totalTime = tiempoFin - inicioTiempo;
            ctlEstructuras.ingresarTiempo("Buscar", "Cola", totalTime);
            if (cancion != null) {
                lblId.setText("" + cancion.getId());
                lblDuracion.setText(cancion.getDuracion() + "");
                lblLanzamiento.setText(cancion.getLanzamiento() + "");
                lblNombre.setText(cancion.getNombre());
            } else {
                JOptionPane.showMessageDialog(null, "No se encontro la Cancion");
            }
            txtDuracionBuscar.setText("");
            txtLanzamientoBuscar.setText("");
            txtNombreBuscar.setText("");
        }
         if (cbxEstructuras.getSelectedIndex() == 5) {
            inicioTiempo = System.nanoTime();
            cancion = arrayList.buscarArrayList(txtDuracionBuscar.getText(), txtNombreBuscar.getText(), txtLanzamientoBuscar.getText());
            tiempoFin = System.nanoTime();
            totalTime = tiempoFin - inicioTiempo;
            ctlEstructuras.ingresarTiempo("Buscar", "ArrayList", totalTime);
            if (cancion != null) {
                lblId.setText("" + cancion.getId());
                lblDuracion.setText(cancion.getDuracion() + "");
                lblLanzamiento.setText(cancion.getLanzamiento() + "");
                lblNombre.setText(cancion.getNombre());
            } else {
                JOptionPane.showMessageDialog(null, "No se encontro la Cancion");
            }
            txtDuracionBuscar.setText("");
            txtLanzamientoBuscar.setText("");
            txtNombreBuscar.setText("");
        }
         
         if (cbxEstructuras.getSelectedIndex() == 6) {
            inicioTiempo = System.nanoTime();
            cancion = array.buscarArray(txtDuracionBuscar.getText(), txtNombreBuscar.getText(), txtLanzamientoBuscar.getText());
            tiempoFin = System.nanoTime();
            totalTime = tiempoFin - inicioTiempo;
            ctlEstructuras.ingresarTiempo("Buscar", "Array", totalTime);
            if (cancion != null) {
                lblId.setText("" + cancion.getId());
                lblDuracion.setText(cancion.getDuracion() + "");
                lblLanzamiento.setText(cancion.getLanzamiento() + "");
                lblNombre.setText(cancion.getNombre());
            } else {
                JOptionPane.showMessageDialog(null, "No se encontro la Cancion");
            }
            txtDuracionBuscar.setText("");
            txtLanzamientoBuscar.setText("");
            txtNombreBuscar.setText("");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        double inicioTiempo;
        double tiempoFin;
        double totalTime;
        if (cbxEstructuras.getSelectedIndex() == 1) {
            inicioTiempo = System.nanoTime();
            listaSimple.modificarListaSimple(txtDuracionModificar.getText(), txtNombreModificar.getText(), txtLanzamientoModificar.getText());
            tiempoFin = System.nanoTime();
            totalTime = tiempoFin - inicioTiempo;
            ctlEstructuras.ingresarTiempo("Modificar", "Lista simple", totalTime);
            listarCancionesLitaSimple();
            txtDuracionModificar.setText("");
            txtLanzamientoModificar.setText("");
            txtNombreModificar.setText("");
        }
        if (cbxEstructuras.getSelectedIndex() == 2) {
            inicioTiempo = System.nanoTime();
            listaDoble.modificarListaDoble(txtDuracionModificar.getText(), txtNombreModificar.getText(), txtLanzamientoModificar.getText());
            tiempoFin = System.nanoTime();
            totalTime = tiempoFin - inicioTiempo;
            ctlEstructuras.ingresarTiempo("Modificar", "Lista doble", totalTime);
            listarCancionesLitaSimple();
            txtDuracionModificar.setText("");
            txtLanzamientoModificar.setText("");
            txtNombreModificar.setText("");
        }
        if (cbxEstructuras.getSelectedIndex() == 3) {
            inicioTiempo = System.nanoTime();
            pila.modificarPila(txtDuracionModificar.getText(), txtNombreModificar.getText(), txtLanzamientoModificar.getText());
            tiempoFin = System.nanoTime();
            totalTime = tiempoFin - inicioTiempo;
            ctlEstructuras.ingresarTiempo("Modificar", "Pila", totalTime);
            listarCancionesLitaSimple();
            txtDuracionModificar.setText("");
            txtLanzamientoModificar.setText("");
            txtNombreModificar.setText("");
        }
        if (cbxEstructuras.getSelectedIndex() == 4) {
            inicioTiempo = System.nanoTime();
            cola.modificarCola(txtDuracionModificar.getText(), txtNombreModificar.getText(), txtLanzamientoModificar.getText());
            tiempoFin = System.nanoTime();
            totalTime = tiempoFin - inicioTiempo;
            ctlEstructuras.ingresarTiempo("Modificar", "Cola", totalTime);
            listarCancionesLitaSimple();
            txtDuracionModificar.setText("");
            txtLanzamientoModificar.setText("");
            txtNombreModificar.setText("");
        }
        if (cbxEstructuras.getSelectedIndex() == 5) {
            inicioTiempo = System.nanoTime();
            arrayList.modificarArrayList(txtDuracionModificar.getText(), txtNombreModificar.getText(), txtLanzamientoModificar.getText());
            tiempoFin = System.nanoTime();
            totalTime = tiempoFin - inicioTiempo;
            ctlEstructuras.ingresarTiempo("Modificar", "ArrayList", totalTime);
            listarCancionesLitaSimple();
            txtDuracionModificar.setText("");
            txtLanzamientoModificar.setText("");
            txtNombreModificar.setText("");
        }
        if (cbxEstructuras.getSelectedIndex() == 6) {
            inicioTiempo = System.nanoTime();
            array.modificarArray(txtDuracionModificar.getText(), txtNombreModificar.getText(), txtLanzamientoModificar.getText());
            tiempoFin = System.nanoTime();
            totalTime = tiempoFin - inicioTiempo;
            ctlEstructuras.ingresarTiempo("Modificar", "Array", totalTime);
            listarCancionesLitaSimple();
            txtDuracionModificar.setText("");
            txtLanzamientoModificar.setText("");
            txtNombreModificar.setText("");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        double inicioTiempo;
        double tiempoFin;
        double totalTime;
        if (cbxEstructuras.getSelectedIndex() == 1) {
            inicioTiempo = System.nanoTime();
            try {
                listaSimple.eliminarListaSimple(Integer.parseInt(cbxRegistrar.getSelectedItem().toString()));
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(pnlEstructuras.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(pnlEstructuras.class.getName()).log(Level.SEVERE, null, ex);
            }
            tiempoFin = System.nanoTime();
            totalTime = tiempoFin - inicioTiempo;
            ctlEstructuras.ingresarTiempo("Eliminar", "Lista simple", totalTime);
            tabla.setModel(new DefaultTableModel());
        }
        if (cbxEstructuras.getSelectedIndex() == 2) {
            inicioTiempo = System.nanoTime();
            try {
                listaDoble.eliminarListaDoble(Integer.parseInt(cbxRegistrar.getSelectedItem().toString()));
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(pnlEstructuras.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(pnlEstructuras.class.getName()).log(Level.SEVERE, null, ex);
            }
            tiempoFin = System.nanoTime();
            totalTime = tiempoFin - inicioTiempo;
            ctlEstructuras.ingresarTiempo("Eliminar", "Lista doble", totalTime);
            tabla.setModel(new DefaultTableModel());
        }

        if (cbxEstructuras.getSelectedIndex() == 3) {
            inicioTiempo = System.nanoTime();
            try {
                pila.eliminarPila(Integer.parseInt(cbxRegistrar.getSelectedItem().toString()));
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(pnlEstructuras.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(pnlEstructuras.class.getName()).log(Level.SEVERE, null, ex);
            }
            tiempoFin = System.nanoTime();
            totalTime = tiempoFin - inicioTiempo;
            ctlEstructuras.ingresarTiempo("Eliminar", "Pila", totalTime);
            tabla.setModel(new DefaultTableModel());
        }

        if (cbxEstructuras.getSelectedIndex() == 4) {
            inicioTiempo = System.nanoTime();
            try {
                cola.eliminarCola(Integer.parseInt(cbxRegistrar.getSelectedItem().toString()));
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(pnlEstructuras.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(pnlEstructuras.class.getName()).log(Level.SEVERE, null, ex);
            }
            tiempoFin = System.nanoTime();
            totalTime = tiempoFin - inicioTiempo;
            ctlEstructuras.ingresarTiempo("Eliminar", "Cola", totalTime);
            tabla.setModel(new DefaultTableModel());
        }
        if (cbxEstructuras.getSelectedIndex() == 5) {
            inicioTiempo = System.nanoTime();
            try {
                arrayList.eliminarArrayList(Integer.parseInt(cbxRegistrar.getSelectedItem().toString()));
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(pnlEstructuras.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(pnlEstructuras.class.getName()).log(Level.SEVERE, null, ex);
            }
            tiempoFin = System.nanoTime();
            totalTime = tiempoFin - inicioTiempo;
            ctlEstructuras.ingresarTiempo("Eliminar", "ArrayList", totalTime);
            tabla.setModel(new DefaultTableModel());
        }
        
        if (cbxEstructuras.getSelectedIndex() == 6) {
            inicioTiempo = System.nanoTime();
            try {
                array.eliminarArray(Integer.parseInt(cbxRegistrar.getSelectedItem().toString()));
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(pnlEstructuras.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(pnlEstructuras.class.getName()).log(Level.SEVERE, null, ex);
            }
            tiempoFin = System.nanoTime();
            totalTime = tiempoFin - inicioTiempo;
            ctlEstructuras.ingresarTiempo("Eliminar", "Array", totalTime);
            tabla.setModel(new DefaultTableModel());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void listarCancionesLitaSimple() {
        tabla.setModel(ctlEstructuras.listarListaSimple());
    }

    private void listarCancionesListaDoble() {
        tabla.setModel(ctlEstructuras.listarLinkedList());
    }

    private void listarCancionesPila() {
        tabla.setModel(ctlEstructuras.listarPila());
    }

    private void listarCancionesCola() {
        tabla.setModel(ctlEstructuras.listarCola());
    }
    private void listarCancionesArrayList() {
        tabla.setModel(ctlEstructuras.listarArrayList());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbxEstructuras;
    private javax.swing.JComboBox<String> cbxRegistrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblLanzamiento;
    private javax.swing.JLabel lblNombre;
    public static javax.swing.JTable tabla;
    private javax.swing.JTextField txtDuracionBuscar;
    private javax.swing.JTextField txtDuracionModificar;
    private javax.swing.JTextField txtLanzamientoBuscar;
    private javax.swing.JTextField txtLanzamientoModificar;
    private javax.swing.JTextField txtNombreBuscar;
    private javax.swing.JTextField txtNombreModificar;
    // End of variables declaration//GEN-END:variables
}
